[package]
version = "0.7.17"
name = "rlviser"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#bevy_atmosphere = "0.10"
# bevy_atmosphere = { git = "https://github.com/ptsd/bevy_atmosphere", branch = "bevy-0.15" }
#bevy_framepace = { version = "0.17", default-features = false }
bevy_framepace = { git = "https://github.com/eero-lehtinen/bevy_framepace", branch = "bevy-15", default-features = false }
bevy_egui = { version = "0.31", default-features = false, features = ["default_fonts", "render"] }
bevy_vector_shapes = "0.9"
byteorder = "1.4.3"
include-flate = "0.3.0"
serde = { version = "1.0.160", features = ["derive", "rc"] }
serde_json = "1.0.96"
walkdir = "2.3.3"
thiserror = "1.0.50"
radsort = "0.1.0"
rust_search = "2.1.0"
crossbeam-channel = "0.5.12"
itertools = "0.13.0"
bincode = "1.3.3"
zip = "2.1.3"
image = { version = "0.25.1", features = ["tga"], default-features = false }

[dependencies.bevy]
version = "0.15"
default-features = false
features = ["bevy_core_pipeline", "bevy_pbr", "bevy_ui", "wayland", "x11", "tga", "default_font", "bevy_gizmos", "bevy_state", "bevy_picking", "bevy_mesh_picking_backend", "bevy_window"]

[features]
default = []
full_load = []
ssao = []
team_goal_barriers = []
debug = []

# Enable a small amount of optimization in debug mode
[profile.dev]
opt-level = 1

# Enable high optimizations for dependencies (incl. Bevy), but not for our code:
[profile.dev.package."*"]
opt-level = 3

[profile.release]
lto = true
strip = true
panic = "abort"

[profile.release-with-debug]
inherits = "release"
debug = true
strip = false

[profile.tiny]
inherits = "release"
opt-level = "s"

[lints.clippy]
all = "warn"
