[package]
name = "rlviser"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.10.0", features = ["bevy_core_pipeline", "bevy_pbr", "bevy_sprite", "bevy_ui", "wayland", "x11", "tga"], default-features = false }
bevy_asset_loader = "0.16.0"
bevy_atmosphere = "0.6.0"
bevy_egui = "0.20.2"
bevy_framepace = { path = "../bevy_framepace", version = "0.12.1", default-features = false }
bevy_mod_picking = { version = "0.13.0", default-features = false, features = ["backend_raycast"] }
byteorder = "1.4.3"
once_cell = "1.17.1"
serde = { version = "1.0.160", features = ["derive"] }
serde_json = "1.0.96"
walkdir = "2.3.3"

[features]
full_load = []

# Enable a small amount of optimization in debug mode
[profile.dev]
opt-level = 1

# Enable high optimizations for dependencies (incl. Bevy), but not for our code:
[profile.dev.package."*"]
opt-level = 3

[profile.release]
lto = true
strip = true
panic = "abort"

[profile.release-with-debug]
inherits = "release"
debug = true
strip = false
lto = false
