[package]
name = "rlviser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.10.0", features = ["wayland"] }
bevy_atmosphere = "0.6.0"
byteorder = "1.4.3"
rand = "0.8.5"
rocketsim_rs = "0.11.0"
smooth-bevy-cameras = "0.8.0"

# Enable a small amount of optimization in debug mode
[profile.dev]
opt-level = 1

# Enable high optimizations for dependencies (incl. Bevy), but not for our code:
[profile.dev.package."*"]
opt-level = 3

[profile.release]
lto = true
strip = true
panic = "abort"
