
[build-system]
requires = ["maturin==1.9.4"]
build-backend = "maturin"

[project]
name = "rlviser"
version = "0.8.2"
requires-python = ">=3.8"
classifiers = [
  "Programming Language :: Rust",
  "Programming Language :: Python :: 3",
]

[tool.maturin]
bindings = "bin"
