[build-system]
requires = ["setuptools>=61.0", "wheel", "setuptools-rust"]
build-backend = "setuptools.build_meta"

[project]
name = "rlviser"
version = "0.8.3"
description = "RLViser - Rocket League replay visualizer"
readme = "README_PYPI.md"
license = {text = "MIT"}
authors = [
    {name = "RLViser Contributors"},
]
requires-python = ">=3.7"
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Rust",
]
dependencies = [
    "torch>=1.13.1",
]

[project.urls]
"Homepage" = "https://github.com/yourusername/rlviser"
"Bug Tracker" = "https://github.com/yourusername/rlviser/issues"

[project.scripts]
rlviser = "rlviser:main"

[tool.setuptools]
packages = ["rlviser"]
include-package-data = true

[tool.setuptools.package-data]
rlviser = ["bin/*"]
