name: Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build - ${{ matrix.platform.os }} (${{ matrix.platform.target }})
    strategy:
      fail-fast: false
      matrix:
        platform:
          - os: ubuntu-22.04
            target: x86_64-unknown-linux-gnu
            bin: pyviser
            
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            bin: pyviser.exe
            
          - os: macos-latest
            target: x86_64-apple-darwin
            bin: pyviser
            
          - os: macos-latest
            target: aarch64-apple-darwin
            bin: pyviser

    runs-on: ${{ matrix.platform.os }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform.target }}
          
      - name: Install Linux dependencies
        if: contains(matrix.platform.os, 'ubuntu')
        run: |
          sudo apt-get update
          sudo apt-get install -y g++ pkg-config libx11-dev libasound2-dev libudev-dev libwayland-dev libxkbcommon-dev
          
      - name: Cache cargo & target directories
        uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.platform.target }}
          
      - name: Build
        run: cargo build --release --target ${{ matrix.platform.target }} --no-default-features --features threaded
        
      - name: Upload binary (Windows)
        if: contains(matrix.platform.os, 'windows')
        uses: actions/upload-artifact@v4
        with:
          name: pyviser-${{ matrix.platform.target }}
          path: target/${{ matrix.platform.target }}/release/pyviser.exe
          
      - name: Upload binary (Unix)
        if: contains(matrix.platform.os, 'ubuntu') || contains(matrix.platform.os, 'macos')
        uses: actions/upload-artifact@v4
        with:
          name: pyviser-${{ matrix.platform.target }}
          path: target/${{ matrix.platform.target }}/release/pyviser