name: Build and release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    name: Release - ${{ matrix.platform.os }}
    strategy:
      matrix:
        platform:
          - os: ubuntu-22.04
            target: x86_64-unknown-linux-gnu
            bin: rlviser
            name: rlviser-x86_64-unknown-linux-gnu.tar.gz

          - os: windows-latest
            target: x86_64-pc-windows-msvc
            bin: rlviser.exe
            name: rlviser-x86_64-pc-windows-msvc.zip

          - os: macos-latest
            target: x86_64-apple-darwin
            bin: rlviser
            name: rlviser-x86_64-apple-darwin.tar.gz

          - os: macos-latest
            target: aarch64-apple-darwin
            bin: rlviser
            name: rlviser-aarch64-apple-darwin.tar.gz

    runs-on: ${{ matrix.platform.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get required packages (Linux only)
        if: contains(matrix.platform.os, 'ubuntu')
        run: sudo apt install g++ pkg-config libx11-dev libasound2-dev libudev-dev libwayland-dev libxkbcommon-dev
      - name: Cache cargo & target directories
        uses: Swatinem/rust-cache@v2
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          target: ${{ matrix.platform.target }}
          args: "--release --no-default-features"
      - name: Upload artifact (Windows)
        if: contains(matrix.platform.os, 'windows')
        uses: actions/upload-artifact@v4.3.3
        with:
          name: binary-windows-${{ matrix.platform.target }}
          path: target/**/release/rlviser.exe
      - name: Upload artifact (Ubuntu)
        if: contains(matrix.platform.os, 'ubuntu')
        uses: actions/upload-artifact@v4.3.3
        with:
          name: binary-linux-${{ matrix.platform.target }}
          path: target/**/release/rlviser
      - name: Upload artifact (macOS)
        if: contains(matrix.platform.os, 'macos')
        uses: actions/upload-artifact@v4.3.3
        with:
          name: binary-macos-${{ matrix.platform.target }}
          path: target/**/release/rlviser
  publish:
    needs: [release, build-wheels]
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: binary-*
          path: target/
          merge-multiple: true
      - name: Download wheels
        uses: actions/download-artifact@v4
        with:
          name: wheels-x86_64-unknown-linux-gnu
          path: dist/wheels-x86_64-unknown-linux-gnu
      - name: Download wheels (Windows)
        uses: actions/download-artifact@v4
        with:
          name: wheels-x86_64-pc-windows-msvc
          path: dist/wheels-x86_64-pc-windows-msvc
      - name: Download wheels (macOS x86_64)
        uses: actions/download-artifact@v4
        with:
          name: wheels-x86_64-apple-darwin
          path: dist/wheels-x86_64-apple-darwin
      - name: Download wheels (macOS aarch64)
        uses: actions/download-artifact@v4
        with:
          name: wheels-aarch64-apple-darwin
          path: dist/wheels-aarch64-apple-darwin
      - name: Publish to GitHub Releases
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./**/target/**
            dist/*/*
          generate_release_notes: true
          body: |
            Extra keybinds for RLViser are included in the README

  build-wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Build wheels
        uses: PyO3/maturin-action@v1
        with:
          command: build
          args: --release -o dist --find-interpreter
      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}
          path: dist
