name: Build and release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    name: Release - ${{ matrix.platform.os }}
    strategy:
      matrix:
        platform:
          - os: ubuntu-22.04
            target: x86_64-unknown-linux-gnu
            bin: rlviser
            name: rlviser-x86_64-unknown-linux-gnu.tar.gz

          - os: windows-latest
            target: x86_64-pc-windows-msvc
            bin: rlviser.exe
            name: rlviser-x86_64-pc-windows-msvc.zip

    runs-on: ${{ matrix.platform.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get required packages (Linux only)
        if: contains(matrix.platform.os, 'ubuntu')
        run: sudo apt install g++ pkg-config libx11-dev libasound2-dev libudev-dev libwayland-dev libxkbcommon-dev
      - name: Cache cargo & target directories
        uses: Swatinem/rust-cache@v2
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          target: ${{ matrix.platform.target }}
          args: "--release --no-default-features"
      - name: Upload artifact (Windows)
        if: contains(matrix.platform.os, 'windows')
        uses: actions/upload-artifact@v4.3.3
        with:
          name: windows
          path: target/**/release/rlviser.exe
      - name: Upload artifact (Ubuntu)
        if: contains(matrix.platform.os, 'ubuntu')
        uses: actions/upload-artifact@v4.3.3
        with:
          name: linux
          path: target/**/release/rlviser
  publish:
    needs: [release]
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: target/
          merge-multiple: true
      - name: Publish to GitHub Releases
        uses: softprops/action-gh-release@v2
        with:
          files: ./**/target/**
          generate_release_notes: true
          body: |
            Extra keybinds for RLViser are included in the README
